### ISSUE TITLE
not work on 1.8.9

### ISSUE THREAD

**Issue by aliakbartnt** [rockyhawk64/CommandPanels#378]
### Terms

- [x] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [x] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [x] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)
- [x] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### What server version are you running?

1.8

### What CommandPanels version are you using?

latest

### What server software are you running?

PaperMC

### What happened?

hi i hava paper laset ver 1.8.9
and plugin not work (not enabel)

### Steps to reproduce the issue

.....

### Expected behavior

....

### Error (optional)

```shell
22:26:10 INFO]: [CommandPanels] Enabling CommandPanels v3.23.1
[22:26:10 INFO]: [CommandPanels] RockyHawk's CommandPanels v3.23.1 Plugin Loading...
[22:26:10 ERROR]: Error occurred while enabling CommandPanels v3.23.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/audience/Audience
        at me.rockyhawk.commandpanels.interaction.commands.CommandRunner.registerBuiltInTags(CommandRunner.java:101) ~[?:?]
        at me.rockyhawk.commandpanels.interaction.commands.CommandRunner.<init>(CommandRunner.java:25) ~[?:?]
        at me.rockyhawk.commandpanels.Context.init(Context.java:135) ~[?:?]
        at me.rockyhawk.commandpanels.Context.<init>(Context.java:101) ~[?:?]
        at me.rockyhawk.commandpanels.CommandPanels.onEnable(CommandPanels.java:24) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.audience.Audience
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 16 more
[22:26:10 INFO]: [CommandPanels] Disabling CommandPanels v3.23.1
[22:26:10 INFO]: RockyHawk's CommandPanels Plugin Disabled (initialization failed).
```

**Comment by aliakbartnt** [comment]
my consol flag : 
"C:\Program Files\Java\jdk-21\bin\java.exe" -Xms1G -Xmx2G -XX:+UseG1GC -XX:MaxGCPauseMillis=150 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -jar paper-1.8.8-445.jar nogui
